POST http://localhost:8080/v1/users
Accept: application/json
Content-Type: application/json

{
  "user": "blue"
}

###
POST http://localhost:8080/v1/stream-feed-credentials
Authorization: Bearer bizUnKitaJqXBEmE+ixqn+U+56zdWWo9OB6bHeR+1kE=
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:8080/v1/stream-chat-credentials
Authorization: Bearer AUcKt/V4lgLPGgIzkLyZQkABJRu+ZuN5W0yRvevcQnA=
Accept: application/json
Content-Type: application/json

{}

###

POST http://localhost:8080/v1/calls
Authorization: Bearer 8yZ0mZLeKxRPVZvbfqLYvPPDMQNuDtz09tMrc5hA5mI=
Accept: application/json
Content-Type: application/json

{
	"id": "123",
	"to": "john"
}

###
DELETE http://localhost:8080/v1/calls/123
Authorization: Bearer v7rZXF3mhuWxLRFkWmINBhOXX26tnroaGMo+mBWH8xM=
Accept: application/json
Content-Type: application/json


###
GET http://localhost:8080/v1/calls
Authorization: Bearer ba8DRRvMqxyBcmny2aS9Ryp9BOcQWYDR8hHX/p45j6Q=
Accept: application/json
Content-Type: application/json
